name: Survey Check

on:
  pull_request:
    types:
      - opened

jobs:
  create_survey_issue: 
    runs-on: ubuntu-latest
    steps:
    - name: Create Issue
      uses: actions/github-script@v7
      id: set-issue
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          console.log(context.repo.owner)
          console.log(context.repo.repo)
          const issue = await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "Copilot survey completion for PR",
            body: "Please complete the survey"
          });
          core.exportVariable('ISSUE_NUMBER', issue.data.number);
    - name: Set Issue Number
      run: echo "{ISSUE_NUMBER}={$ISSUE_NUMBER}" >> "$GITHUB_ENV"
    - name: Comment on PR
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # In the GitHub API, PRs and issues are the same thing. Below, we're creating a comment on the PR so the reference to "issue" overlaps
        script: |
          const pull_comment = await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "Heads up @${{github.event.pull_request.user.login}}, please complete the survey found in https://github.com/${{ github.repository }}/issues/${{ env.ISSUE_NUMBER }} before merging this PR."
          });
  survey_check:
    runs-on: ubuntu-latest
    steps:
    - name: Check env var
      run: echo $ISSUE_NUMBER
    - name: Update Check Run Status
      uses: actions/github-script@v7 
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const conclusion = 'failure';
          const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
          await octokit.rest.checks.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: 'Survey Check',
            head_sha: context.sha,
            status: 'in-progress',
            output: {
              title: 'Survey Check',
              summary: 'Survey completion check',
            }
          });
