name: Survey Check

on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - main

jobs:
  create_survey_issue: 
    runs-on: ubuntu-latest
    steps:
    - name: Create Issue
      uses: actions/github-script@v7
      id: set-issue
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          console.log(context.repo.owner)
          console.log(context.repo.repo)
          const issue = await github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "Copilot survey completion for PR",
            body: "Please complete the survey",
          });
          console.log(issue.data.number)
    - name: Set Issue Number
      run: echo "ISSUE_NUMBER=${{ steps.create_issue.outputs.result }}" >> $GITHUB_ENV
  survey_check:
    runs-on: ubuntu-latest
    steps:
    - name: Update Check Run Status
      uses: actions/github-script@v7 
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const conclusion = 'failure';
          const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
          await octokit.rest.checks.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: 'Survey Check',
            head_sha: context.sha,
            status: 'in-progress',
            output: {
              title: 'Survey Check',
              summary: 'Survey completion check',
            }
          });
